### ISSUE TITLE
Landscape Support 

### ISSUE THREAD

**Issue by Kautenja** [tapptitude/TTSegmentedControl#1]
When the orientation changes to landscape,

1.    the control doesn't resize to accommodate the new screen size. 
2.   If an option is selected, the slider moves to an awkward position in the uppermost left point of the view. The block in didSelectItemWith doesn't execute and further selection is no longer possible in this orientation. 
3.   When switched back to portrait, the slider stays in the top left corner, but functionality is repaired. If another selection is made, the slider will correct its position to highlight the selection and the didSelectItemWith block executes correctly.

*   I've noticed this issue in several locations of my implementation on both iPads and iPhones.
*   I've tested this on iOS10.x.x

**Comment by markkrenek** [comment]
I managed to hack the code to fix this, but it's not pretty. The main problem is that layoutSubviews() only reconfigures the control the first time it is called. It really needs to reconfigure on any size change. My hack is to remove most/all the control's subviews at the top of layoutSubviews() and then let it completely rebuild everything. Add this code to the top of layoutSubviews() right after super.layoutSubviews():

```
isConfigurated = false
containerView.removeFromSuperview()
thumbContainerView.removeFromSuperview()
thumbView.removeFromSuperview()
selectedLabelsView.removeFromSuperview()
containerView = UIView()
thumbContainerView = UIView()
thumbView = UIView()
selectedLabelsView = UIView()
allItemLabels.removeAll()
allSelectedItemLabels.removeAll()
```

This hack WON'T restore the selected item correctly. That requires another hack.

I'm not preparing a PR for this since this isn't really the correct way to fix this issue.

**Comment by EfraimB** [comment]
Not need for hacks guys, both problems were solved. Thank you a lot for reporting this problem.
